# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello CLI"
  homepage "https://github.com/sameersbn/test-repo"
  version "0.0.48"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.48/hello_macOS_amd64"
      sha256 "e258f23118426e71d198b50e105488c6a77fa660482364669da74b5d6fc18f8f"

      def install
        bin.install "hello"
        chmod 0555, bin/"hello"
        generate_completions_from_executable(bin/"hello", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.48/hello_macOS_arm64"
      sha256 "20167157b62b9d2a31327b6cd3b367957bdd5fb3c4885c182e4aa10322ea6089"

      def install
        bin.install "hello"
        chmod 0555, bin/"hello"
        generate_completions_from_executable(bin/"hello", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.48/hello_linux_armv6"
      sha256 "3d2c66331547c9cbfbd23d41d4f2a8bda18e19552e86d1f5661c8ab91d74af59"

      def install
        bin.install "hello"
        chmod 0555, bin/"hello"
        generate_completions_from_executable(bin/"hello", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.48/hello_linux_arm64"
      sha256 "be521ea7cd99921ecc80f89578f532f4ca49ae844f02736633e90105cb94ea7d"

      def install
        bin.install "hello"
        chmod 0555, bin/"hello"
        generate_completions_from_executable(bin/"hello", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.48/hello_linux_amd64"
      sha256 "9986914c2d70866ad52460b3edbcba327113553efd5cceab550b68bc0835dfd9"

      def install
        bin.install "hello"
        chmod 0555, bin/"hello"
        generate_completions_from_executable(bin/"hello", shells: [:bash, :zsh])
      end
    end
  end
end
