# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello CLI"
  homepage "https://github.com/sameersbn/test-repo"
  version "0.0.46"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.46/hello_macOS_arm64"
      sha256 "69983355f30c0c7542406df6668ae8d1ceccadd49dfe0089a53a7125f6fbdb24"

      def install
        bin.install "hello_macOS_arm64" => "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.46/hello_macOS_amd64"
      sha256 "a1bff9d6ab41e2d98718ec32961f794fb79860edfec98ad9d09d215a6e2b7f3e"

      def install
        bin.install "hello_macOS_amd64" => "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.46/hello_linux_amd64"
      sha256 "93a1d8721390b88d0545ab7490fe08c35c6c3dea1c003a39b7ff5ff35c68d579"

      def install
        bin.install "hello_linux_amd64" => "hello"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.46/hello_linux_armv6"
      sha256 "119f74a0aea45dc53e4f4185be5a52ac46f23b40086efd9233137daf7fb32ac4"

      def install
        bin.install "hello_linux_armv6" => "hello"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sameersbn/test-repo/releases/download/v0.0.46/hello_linux_arm64"
      sha256 "b622d5f5089baaed824d34fb87ba67d11fd7546ce8366feed2b3e0d9ddde9d2e"

      def install
        bin.install "hello_linux_arm64" => "hello"
      end
    end
  end
end
